# Generated by Django 5.2.5 on 2025-11-20 10:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='서명')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='저자')),
                ('publisher', models.CharField(blank=True, max_length=120, verbose_name='출판사')),
                ('pub_year', models.CharField(blank=True, max_length=10, verbose_name='출판년도')),
                ('call_number', models.CharField(blank=True, max_length=50, verbose_name='청구기호')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='표지 이미지')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='재고 수')),
            ],
            options={
                'verbose_name': '도서',
                'verbose_name_plural': '도서',
                'unique_together': {('title', 'author', 'publisher', 'pub_year', 'call_number')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='리뷰 내용')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='도서')),
                ('user', models.ForeignKey(blank=True, help_text='작성자(선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'ordering': ['-created_at'],
            },
        ),
    ]
