# Generated by Django 5.2.5 on 2026-04-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, null=True, verbose_name='표지 링크'),
        ),
    ]
