# Generated by Django 5.2.5 on 2026-04-20 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_isbn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_books', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사용자'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=True, verbose_name='익명 여부'),
        ),
    ]
