# Generated by Django 5.2.5 on 2026-04-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_likes_book_liked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='s_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='s_태그'),
        ),
        migrations.AddField(
            model_name='book',
            name='sortnum',
            field=models.CharField(blank=True, default=0, verbose_name='분류 번호'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag1',
            field=models.CharField(blank=True, max_length=50, verbose_name='태그1'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag2',
            field=models.CharField(blank=True, max_length=50, verbose_name='태그2'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag3',
            field=models.CharField(blank=True, max_length=50, verbose_name='태그3'),
        ),
        migrations.AddField(
            model_name='book',
            name='y_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='y_태그'),
        ),
    ]
