# Generated by Django 5.2.5 on 2026-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_s_tag_book_sortnum_book_tag1_book_tag2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sortnum',
            field=models.CharField(blank=True, default=0, max_length=50, verbose_name='분류 번호'),
        ),
    ]
