# Generated by Django 5.2.5 on 2026-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_sortnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='y_tag',
        ),
        migrations.AddField(
            model_name='book',
            name='add_date',
            field=models.CharField(blank=True, max_length=200, verbose_name='등록일'),
        ),
        migrations.AddField(
            model_name='book',
            name='booknum',
            field=models.CharField(blank=True, max_length=200, verbose_name='옥야 번호'),
        ),
        migrations.AddField(
            model_name='book',
            name='g_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='g_태그'),
        ),
    ]
