# Generated by Django 5.2.5 on 2026-04-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_y_tag_book_add_date_book_booknum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booknum',
            field=models.TextField(blank=True, verbose_name='옥야 번호'),
        ),
    ]
