# Generated by Django 5.2.5 on 2026-05-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_booknum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='g_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='장르태그'),
        ),
        migrations.AlterField(
            model_name='book',
            name='s_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='특수태그'),
        ),
    ]
