# Generated by Django 5.2.5 on 2025-12-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='library_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='학생증 도서관 번호'),
        ),
    ]
